# Generated by Django 5.2.6 on 2025-09-27 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_servicecategory_predefinedservice_shopportfolioimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('round', 'Round'), ('oval', 'Oval'), ('square', 'Square'), ('heart', 'Heart'), ('oblong', 'Oblong'), ('diamond', 'Diamond')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('characteristics', models.TextField(help_text='Key characteristics of this face shape')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHaircutPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customer_photos/')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in face shape detection')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haircut_photos', to=settings.AUTH_USER_MODEL)),
                ('detected_face_shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haircut_suggestions.faceshape')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='HaircutStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('example_image', models.ImageField(blank=True, upload_to='haircut_examples/')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('maintenance_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haircut_styles', to='shops.servicecategory')),
                ('suitable_face_shapes', models.ManyToManyField(related_name='suitable_haircuts', to='haircut_suggestions.faceshape')),
            ],
        ),
        migrations.CreateModel(
            name='HaircutSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='How well this style matches the face shape')),
                ('reason', models.TextField(blank=True, help_text='Why this style was suggested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haircut_suggestions.customerhaircutphoto')),
                ('haircut_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haircut_suggestions.haircutstyle')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('customer_photo', 'haircut_style')},
            },
        ),
        migrations.AddField(
            model_name='customerhaircutphoto',
            name='suggested_styles',
            field=models.ManyToManyField(through='haircut_suggestions.HaircutSuggestion', to='haircut_suggestions.haircutstyle'),
        ),
    ]
