# Generated by Django 5.2.6 on 2025-09-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut_suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircutstyle',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='haircutstyle',
            name='length_category',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('any', 'Any')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='haircutstyle',
            name='overlay_image',
            field=models.ImageField(blank=True, upload_to='style_overlays/'),
        ),
    ]
