# Generated by Django 5.2.6 on 2025-09-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('shops', '0003_servicecategory_predefinedservice_shopportfolioimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='shops.shopservice'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='special_request',
            field=models.TextField(blank=True, help_text='Any special requests or notes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration in minutes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
